<a href="https://colab.research.google.com/github/zlzonhenu/RNN-tutorial/blob/master/RNN_hihello_and_charseq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(0)

In [0]:
#declare dictionary
char_set = ['h','i','e','l','o']

In [0]:
#hyper parameters
input_size = len(char_set)
hidden_size = len(char_set)
learning_rate = 0.1

In [0]:
#data setiing
x_data = [[0,1,0,2,3,3]]
x_one_hot = [[[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [1, 0, 0, 0, 0],
              [0, 0, 1, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0]]]
y_data = [[1, 0, 2, 3, 3, 4]]

In [0]:
#transform as torch tensor variable
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

In [0]:
#declare RNN
rnn = torch.nn.RNN(input_size, hidden_size, batch_first = True)
#batch_first guarantees the order of output

In [0]:
#loss & optimizer setting
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters(), learning_rate)

In [32]:
ouputs, _status = rnn(X)
print(outputs.size())
print(Y.size())
print(Y.view(-1).size())
print(outputs.view(-1,input_size).size())
print(Y)
print(outputs.data.numpy())
print(outputs.data.numpy().argmax(axis=0))
print(outputs.data.numpy().argmax(axis=1))
print(outputs.data.numpy().argmax(axis=2))
print(result)
result.shape

torch.Size([1, 6, 5])
torch.Size([1, 6])
torch.Size([6])
torch.Size([6, 5])
tensor([[1, 0, 2, 3, 3, 4]])
[[[-0.99561334  0.9885677  -0.9742647  -0.99791664 -0.99727935]
  [ 0.9994566  -0.9916573  -0.99999994  0.9999962  -0.96832657]
  [-0.9999745  -0.9850392   0.99496484 -0.97098386 -0.9999968 ]
  [-0.9949256  -0.9774894  -1.          0.9999374  -0.99998665]
  [-0.9996332  -0.99999845 -0.9994085   0.9706184  -0.23617315]
  [-0.99980384 -0.9999955  -0.98764664 -0.86582017  0.9754412 ]]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 2 1 5]]
[[1 3 2 3 3 4]]
[[1 3 2 3 3 4]]


(1, 6)

criterian : 각 카테고리에 대한 확률을 나타낸다. 그 확률 중 가장 높은 값을 가지는 클래스와 정답 클래스의 확률 차이를 줄이게 하는 함수

cirterian(x, class)

삼차원일때
numpy().argmax(axis=0) 삼차원 배열끼리 비교 
numpy().argmax(axis=1) 같은 열끼리 비교
numpy().argmax(axis=2) 같은 행끼리 비교
비교해서 가장 큰 값에 대한 인덱스 반환

np.squeeze(result)
축 정보를 주지 않아서 모든 1차원을 없앤다.
여기서는 (1,6)을 (6)인 리스트로 변환한다.

In [10]:
#start training
for i in range(100):
  optimizer.zero_grad()
  outputs, _status = rnn(X)
  loss = criterion(outputs.view(-1, input_size), Y.view(-1))
  loss.backward()
  optimizer.step()

  result = outputs.data.numpy().argmax(axis=2)
  #result array의 차원을 
  result_str = ''.join([char_set[c] for c in np.squeeze(result)])
  print(i, 'loss: ', loss.item(), 'Prediction: ', result, 'true Y: ', y_data, 'Prediction str: ', result_str)

0 loss:  1.4931949377059937 Prediction:  [[1 4 1 1 4 4]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  ioiioo
1 loss:  1.33371102809906 Prediction:  [[1 3 2 3 1 4]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  ilelio
2 loss:  1.215294599533081 Prediction:  [[2 3 2 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  elelll
3 loss:  1.1131387948989868 Prediction:  [[2 3 2 3 3 3]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  elelll
4 loss:  1.0241864919662476 Prediction:  [[2 3 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  elello
5 loss:  0.9573140740394592 Prediction:  [[2 3 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  elello
6 loss:  0.910200297832489 Prediction:  [[2 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  ehello
7 loss:  0.8731765151023865 Prediction:  [[1 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  ihello
8 loss:  0.8399617671966553 Prediction:  [[1 0 2 3 3 4]] true Y:  [[1, 0, 2, 3, 3, 4]] Prediction str:  ihello
9 los